version: "3"
services:
  backend:
    build: ./backend
    container_name: backend
    tty: true
    volumes:
      - ./backend:/app
      - back-node-modules:/app/node_modules
    networks:
      - proxy-backend
  frontend:
    build: ./frontend
    container_name: frontend
    volumes:
      - front-build:/app/build
  nginx:
    container_name: proxy
    restart: always
    image: nginx
    depends_on:
      - frontend
      - backend
    ports:
      - "80:80"
    volumes:
      - "front-build:/var/www/html/"
      - "./nginx/default.conf:/etc/nginx/conf.d/default.conf"
    networks:
      - proxy-backend
networks:
  proxy-backend:
    driver: bridge
volumes:
  front-build:
    driver: local
  back-node-modules:
    driver: local
